#!/bin/bash
TOOLS="$(dirname "$0")/tools.json" 
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)" 
ASCIIDUCK=$(<"$SCRIPT_DIR/duck-letter.txt")
if ! jq --version >/dev/null 2>&1; then
    echo "You need jq to use this tool. Please install jq first."
    exit 1
fi

if [[ -z "$1" ]]; then
  echo "$ASCIIDUCK"
  echo ""
  echo ""
  echo "Use --list to list all tools aviable or [tool] to open documentation"
  exit 0
fi

if [[ "$1" == --list ]]; then
  echo "All tools:"
  jq -r 'keys[]' "$TOOLS" | sed 's/^/    /'
  exit 0
fi

if jq -e --arg cmd "$1" '.[$cmd]' "$TOOLS" >/dev/null; then
  URL=$(jq -r --arg cmd "$1" '.[$cmd]' "$TOOLS")
  echo "Open Doc of $1"
  xdg-open "$URL"
  exit 0
else
  echo "Sorry :'( the $1 tool dont implemented yet. You can aport in https://github.com/docduck"
  exit 1
fi
